# Generated by Django 4.0.5 on 2022-06-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick', '0002_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
