# Generated by Django 4.0.5 on 2022-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_post_gender_remove_post_text_remove_post_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='firstname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
